import { ISchemeSeed } from './schemesData.js';

export const stateSchemesData: ISchemeSeed[] = [
  // ==========================================
  // 1. GUJARAT STATE SCHEMES
  // ==========================================
  {
    title: 'Mukhyamantri Amrutam (MAA) Yojana',
    slug: 'gujarat-mukhyamantri-amrutam-maa-yojana',
    categorySlug: 'health-wellness',
    ministry: 'Health and Family Welfare Department, Government of Gujarat',
    department: 'Commissionerate of Health, Medical Services and Medical Education',
    schemeLevel: 'State',
    state: 'Gujarat',
    shortDescription: 'Cashless tertiary medical and surgical healthcare coverage up to ₹5 Lakh per year for BPL and lower-middle-class families in Gujarat.',
    description: 'Mukhyamantri Amrutam (MAA) Yojana and MAA Vatsalya is a flagship tertiary healthcare scheme of Gujarat providing cashless hospitalization coverage up to ₹5,00,000 per family per year for catastrophic illnesses, cardiac surgeries, neurosurgeries, burns, cancer, and kidney transplants across empaneled hospitals.',
    benefitType: 'Insurance',
    financialBenefit: 'Cashless medical treatment cover up to ₹5,00,000 per family per year + ₹300 conveyance per hospitalization',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 100,
      gender: 'All',
      maxIncome: 400000,
      eligibleStates: ['Gujarat'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Unemployed', 'Student', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['MAA / MAA Vatsalya Card', 'Aadhaar Card', 'Income Certificate issued by Mamlatdar / TDO', 'Ration Card', 'Passport Photo'],
    applicationProcess: ['Visit nearest Taluka Kiosk, Civic Centre, or District Hospital.', 'Biometrics and thumb impression are authenticated against Aadhaar.', 'Receive biometric MAA Health Smart Card on the spot.'],
    officialUrl: 'https://magujarat.com/',
    helplineNumber: '1800-233-1022',
    tags: ['Gujarat', 'Healthcare', 'Cashless Hospital', 'Surgery', 'State Scheme'],
  },
  {
    title: 'Kisan Suryodaya Yojana (Gujarat)',
    slug: 'gujarat-kisan-suryodaya-yojana',
    categorySlug: 'agriculture-rural-development',
    ministry: 'Energy and Petrochemicals Department, Government of Gujarat',
    department: 'Gujarat Urja Vikas Nigam Limited (GUVNL)',
    schemeLevel: 'State',
    state: 'Gujarat',
    shortDescription: 'Guaranteed 3-phase daytime electricity supply (5 AM to 9 PM) for farm irrigation across Gujarat.',
    description: 'Kisan Suryodaya Yojana ensures daytime 3-phase agricultural power supply between 5:00 AM and 9:00 PM to farmers in Gujarat, replacing night-time hazardous farm visits and safeguarding farmers from wild animals while enhancing irrigation efficiency.',
    benefitType: 'Subsidy',
    financialBenefit: '100% state-funded dedicated 66kV transmission feeder network and subsidized 3-phase daytime power supply',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 85,
      gender: 'All',
      maxIncome: 2500000,
      eligibleStates: ['Gujarat'],
      eligibleOccupations: ['Farmer'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['7/12 & 8A Land Revenue Record', 'Agricultural Electricity Connection Consumer Number (DISCOM)', 'Aadhaar Card'],
    applicationProcess: ['Feeder conversion automatically managed by DISCOM (PGVCL, DGVCL, MGVCL, UGVCL).', 'Farmers verify feeder conversion status via GUVNL portal.'],
    officialUrl: 'https://guvnl.gujarat.gov.in/',
    helplineNumber: '19122 / 1800-233-3001',
    tags: ['Gujarat', 'Agriculture', 'Daytime Power', 'Irrigation', 'State Scheme'],
  },
  {
    title: 'Mukhyamantri Yuva Swavalamban Yojana (MYSY)',
    slug: 'gujarat-mukhyamantri-yuva-swavalamban-yojana-mysy',
    categorySlug: 'education-skill-training',
    ministry: 'Education Department, Government of Gujarat',
    department: 'Knowledge Consortium of Gujarat (KCG)',
    schemeLevel: 'State',
    state: 'Gujarat',
    shortDescription: 'Higher education tuition fee scholarship up to ₹2,00,000/year and hostel stipend for meritorious Gujarat students.',
    description: 'MYSY provides comprehensive financial assistance to meritorious Gujarat students securing 80+ percentile in 10th/12th board exams with household income under ₹6 Lakh, covering 50% tuition fees (up to ₹2 Lakh for Medical, ₹50,000 for Engineering/Pharmacy) plus hostel and book allowances.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: 'Up to ₹2,00,000/year tuition fee + ₹12,000/year hostel allowance + ₹10,000 one-time book equipment grant',
    eligibilityCriteria: {
      minAge: 16,
      maxAge: 30,
      gender: 'All',
      maxIncome: 600000,
      eligibleStates: ['Gujarat'],
      eligibleOccupations: ['Student'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Class 10th / 12th Marksheet (80+ Percentile)', 'Gujarat Domicile Certificate', 'Income Certificate (< ₹6 Lakh)', 'College Admission Letter & Fee Receipt', 'Bank Passbook'],
    applicationProcess: ['Register on mysy.guj.nic.in after securing college admission.', 'Upload marksheets, income certificate, and tuition fee receipt.', 'Submit physical documents to designated Help Center college for verification.'],
    officialUrl: 'https://mysy.guj.nic.in/',
    helplineNumber: '079-26566000',
    tags: ['Gujarat', 'Higher Education', 'Scholarship', 'Tuition Waiver', 'State Scheme'],
  },
  {
    title: 'Vahli Dikri Yojana (Gujarat)',
    slug: 'gujarat-vahli-dikri-yojana',
    categorySlug: 'women-child-development',
    ministry: 'Women and Child Development Department, Government of Gujarat',
    department: 'Directorate of Women and Child Development',
    schemeLevel: 'State',
    state: 'Gujarat',
    shortDescription: '₹1,10,000 milestone financial incentive for first and second girl child to promote female education and curb female foeticide.',
    description: 'Vahli Dikri Yojana is a pioneering girl-child empowerment scheme of Gujarat providing direct milestone cash assistance totaling ₹1,10,000: ₹4,000 on Class 1 enrollment, ₹6,000 on Class 9 enrollment, and ₹1,00,000 on attaining 18 years for higher education or marriage.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹1,10,000 cumulative cash assistance transferred directly into beneficiary girl child account across 3 milestones',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 18,
      gender: 'Female',
      maxIncome: 200000,
      eligibleStates: ['Gujarat'],
      eligibleOccupations: ['Student', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: ['Girl Child'],
    },
    requiredDocuments: ['Girl Child Birth Certificate', 'Parents Aadhaar Card', 'Gujarat Domicile Proof', 'Income Certificate (< ₹2 Lakh)', 'Bank Passbook in Girl Child Name'],
    applicationProcess: ['Apply at nearest Anganwadi Centre, CDPO office, or Gram Panchayat within 1 year of girl child birth.', 'Verification conducted by Child Development Project Officer.'],
    officialUrl: 'https://wcd.gujarat.gov.in/',
    helplineNumber: '181 (Abhayam Women Helpline)',
    tags: ['Gujarat', 'Girl Child', 'DBT', 'Beti Bachao', 'State Scheme'],
  },
  {
    title: 'Saat Pagla Khedut Kalyan Na (Gujarat)',
    slug: 'gujarat-saat-pagla-khedut-kalyan-na',
    categorySlug: 'agriculture-rural-development',
    ministry: 'Agriculture, Farmers Welfare and Co-operation Department, Government of Gujarat',
    department: 'Directorate of Agriculture',
    schemeLevel: 'State',
    state: 'Gujarat',
    shortDescription: 'Subsidies for indigenous cow maintenance (₹900/month), farm godowns (₹30,000), battery spray pumps, and solar insect traps.',
    description: 'Saat Pagla Khedut Kalyan Na consists of 7 comprehensive agrarian welfare umbrellas in Gujarat, including ₹10,800/year assistance for maintaining indigenous desi cows in natural farming, ₹30,000 subsidy for on-farm crop storage godowns, and subsidized multi-purpose agricultural toolkits.',
    benefitType: 'Subsidy',
    financialBenefit: '₹900/month cow maintenance DBT + ₹30,000 crop godown subsidy + 75% subsidy on battery sprayers',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 80,
      gender: 'All',
      maxIncome: 1500000,
      eligibleStates: ['Gujarat'],
      eligibleOccupations: ['Farmer'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['7/12 & 8A Land Records', 'Aadhaar Card', 'Desi Cow Tagging Identification Certificate', 'Bank Passbook'],
    applicationProcess: ['Apply online on ikhedut.gujarat.gov.in portal.', 'Select specific Paglu component.', 'Submit application with revenue record to District Agriculture Officer.'],
    officialUrl: 'https://ikhedut.gujarat.gov.in/',
    helplineNumber: '1800-180-1551',
    tags: ['Gujarat', 'Natural Farming', 'Desi Cow Subsidy', 'Farm Godown', 'State Scheme'],
  },
  {
    title: 'Mukhyamantri Mahila Utkarsh Yojana (MMUY)',
    slug: 'gujarat-mukhyamantri-mahila-utkarsh-yojana',
    categorySlug: 'business-msme-entrepreneurship',
    ministry: 'Women and Child Development Department, Government of Gujarat',
    department: 'Gujarat Livelihood Promotion Company (GLPC)',
    schemeLevel: 'State',
    state: 'Gujarat',
    shortDescription: '₹1,00,000 collateral-free and 100% interest-free bank loan for Joint Liability Earning Groups (JLEG) of women.',
    description: 'MMUY empowers rural and urban women in Gujarat by mobilizing them into 10-member Joint Liability Earning Groups (JLEG) and providing ₹1,00,000 zero-interest bank credit for establishing micro-enterprises, with the state government bearing all interest charges.',
    benefitType: 'Loan / Credit',
    financialBenefit: '₹1,00,000 zero-interest (0%) collateral-free credit per women group + stamp duty exemption',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 59,
      gender: 'Female',
      maxIncome: 300000,
      eligibleStates: ['Gujarat'],
      eligibleOccupations: ['Self-Employed', 'Artisan / Craftsperson', 'Street Vendor', 'Business Owner / MSME', 'Farmer'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aadhaar Cards of all 10 group members', 'Gujarat Domicile Proof', 'Joint Group Bank Account Details', 'Ration Card'],
    applicationProcess: ['Form a 10-member JLEG group through Anganwadi or GLPC taluka coordinator.', 'Apply through designated public sector or cooperative bank.'],
    officialUrl: 'https://glpc.gujarat.gov.in/',
    helplineNumber: '079-23253600',
    tags: ['Gujarat', 'Women MSME', 'Zero Interest Loan', 'SHG', 'State Scheme'],
  },

  // ==========================================
  // 2. MAHARASHTRA STATE SCHEMES
  // ==========================================
  {
    title: 'Mukhyamantri Majhi Ladki Bahin Yojana',
    slug: 'maharashtra-mukhyamantri-majhi-ladki-bahin-yojana',
    categorySlug: 'women-child-development',
    ministry: 'Women and Child Development Department, Government of Maharashtra',
    department: 'Directorate of Women and Child Development',
    schemeLevel: 'State',
    state: 'Maharashtra',
    shortDescription: 'Direct cash DBT of ₹1,500 per month (₹18,000/year) to women aged 21-65 years in Maharashtra.',
    description: 'Majhi Ladki Bahin Yojana provides unconditional monthly financial assistance of ₹1,500 directly into Aadhaar-linked bank accounts of economically backward women residents of Maharashtra to enhance health, nutrition, and financial independence.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹1,500 per month (₹18,000 annually) transferred directly through DBT',
    eligibilityCriteria: {
      minAge: 21,
      maxAge: 65,
      gender: 'Female',
      maxIncome: 250000,
      eligibleStates: ['Maharashtra'],
      eligibleOccupations: ['Self-Employed', 'Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aadhaar Card', 'Maharashtra Domicile Certificate / Ration Card (Yellow/Orange)', 'Income Certificate (< ₹2.5 Lakh) or Yellow/Orange Ration Card', 'Aadhaar-seeded Bank Passbook'],
    applicationProcess: ['Apply online via Nari Shakti Doot App or ladkibahin.maharashtra.gov.in.', 'Fill applicant profile, upload Aadhaar and bank details.', 'Verification done by Anganwadi Sevika / Ward Officer.'],
    officialUrl: 'https://ladkibahin.maharashtra.gov.in/',
    helplineNumber: '181 / 022-22027050',
    tags: ['Maharashtra', 'Women Empowerment', 'Monthly DBT', 'Ladki Bahin', 'State Scheme'],
  },
  {
    title: 'Mahatma Jyotirao Phule Jan Arogya Yojana (MJPJAY)',
    slug: 'maharashtra-mahatma-jyotirao-phule-jan-arogya-yojana',
    categorySlug: 'health-wellness',
    ministry: 'Public Health Department, Government of Maharashtra',
    department: 'State Health Assurance Society (SHAS)',
    schemeLevel: 'State',
    state: 'Maharashtra',
    shortDescription: 'Cashless hospitalisation health coverage up to ₹5,00,000 per family per year across 1,356 procedures for all citizens of Maharashtra.',
    description: 'MJPJAY is a universalized flagship health assurance scheme in Maharashtra providing 100% cashless medical and surgical care up to ₹5 Lakh per family per year across 1,356 medical therapies and 120 follow-up procedures in empaneled government and private hospitals.',
    benefitType: 'Insurance',
    financialBenefit: 'Cashless health cover up to ₹5,00,000 per family per year covering all 1,356 medical and surgical procedures',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 100,
      gender: 'All',
      maxIncome: 10000000,
      eligibleStates: ['Maharashtra'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Employed / Salaried', 'Unemployed', 'Student', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Ration Card (Yellow / Orange / White)', 'Aadhaar Card', 'Voter ID or Domicile Certificate of Maharashtra'],
    applicationProcess: ['Visit any empaneled government or private hospital network.', 'Meet Arogyamitra at hospital helpdesk.', 'Show Ration Card and Aadhaar for instant biometric authorization and cashless admission.'],
    officialUrl: 'https://www.jeevandayee.gov.in/',
    helplineNumber: '155388 / 1800-120-8040',
    tags: ['Maharashtra', 'Universal Healthcare', 'Cashless Hospital', 'MJPJAY', 'State Scheme'],
  },
  {
    title: 'Namo Shetkari Mahasanman Nidhi Yojana',
    slug: 'maharashtra-namo-shetkari-mahasanman-nidhi-yojana',
    categorySlug: 'agriculture-rural-development',
    ministry: 'Agriculture Department, Government of Maharashtra',
    department: 'Commissionerate of Agriculture Maharashtra',
    schemeLevel: 'State',
    state: 'Maharashtra',
    shortDescription: 'State supplementary cash assistance of ₹6,000 per year (total ₹12,000/year with PM-KISAN) for landholding farmers in Maharashtra.',
    description: 'Namo Shetkari Mahasanman Nidhi Yojana provides an additional ₹6,000 per year in three installments of ₹2,000 directly to farmer families in Maharashtra, complementing the central PM-KISAN payout to double annual agrarian support to ₹12,000.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹6,000 per year (total ₹12,000/year combined with PM-KISAN) directly credited into bank account',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 85,
      gender: 'All',
      maxIncome: 2500000,
      eligibleStates: ['Maharashtra'],
      eligibleOccupations: ['Farmer'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aadhaar Card linked to Bank Account', 'PM-KISAN Beneficiary Registration ID', '7/12 Land Revenue Extract of Maharashtra'],
    applicationProcess: ['Automatic enrollment for all verified PM-KISAN beneficiary farmers in Maharashtra.', 'Check DBT disbursement on nsmny.mahait.org.'],
    officialUrl: 'https://nsmny.mahait.org/',
    helplineNumber: '020-25537021',
    tags: ['Maharashtra', 'Farmer Support', 'DBT', 'PM-KISAN Topup', 'State Scheme'],
  },
  {
    title: 'Mukhyamantri Yuva Karya Prashikshan Yojana (Maharashtra)',
    slug: 'maharashtra-yuva-karya-prashikshan-yojana',
    categorySlug: 'education-skill-training',
    ministry: 'Skill Development, Employment, Entrepreneurship and Innovation Department, Government of Maharashtra',
    department: 'Commissionerate of Skill Development',
    schemeLevel: 'State',
    state: 'Maharashtra',
    shortDescription: 'Monthly stipend of ₹6,000 to ₹10,000 for 6 months on-the-job internship training for Maharashtra youth.',
    description: 'This scheme provides practical working training and corporate apprenticeships to youth who have passed 12th, ITI, Diploma, Graduation, or Post-Graduation in Maharashtra, with the state government transferring stipends directly into bank accounts for 6 months.',
    benefitType: 'Skill Training',
    financialBenefit: '₹6,000/month (12th Pass), ₹8,000/month (ITI/Diploma), ₹10,000/month (Graduates/Post-Graduates) for 6 months',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 35,
      gender: 'All',
      maxIncome: 800000,
      eligibleStates: ['Maharashtra'],
      eligibleOccupations: ['Student', 'Unemployed'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Educational Certificates / Degree Marksheet', 'Aadhaar Card', 'Maharashtra Domicile Certificate', 'Bank Passbook'],
    applicationProcess: ['Register on rojgar.mahaswayam.gov.in portal.', 'Apply for industry internship matching education profile.', 'Complete monthly attendance for direct stipend transfer.'],
    officialUrl: 'https://rojgar.mahaswayam.gov.in/',
    helplineNumber: '1800-120-8041',
    tags: ['Maharashtra', 'Skill Training', 'Internship Stipend', 'Youth Employment', 'State Scheme'],
  },
  {
    title: 'Lek Ladki Yojana (Maharashtra)',
    slug: 'maharashtra-lek-ladki-yojana',
    categorySlug: 'women-child-development',
    ministry: 'Women and Child Development Department, Government of Maharashtra',
    department: 'Directorate of Women and Child Development',
    schemeLevel: 'State',
    state: 'Maharashtra',
    shortDescription: '₹1,01,000 cumulative cash assistance from birth to age 18 for girl children born in yellow/orange ration card families.',
    description: 'Lek Ladki Yojana supports girl children born on or after April 1, 2023, across five life milestones: ₹5,000 on birth, ₹6,000 on Class 1, ₹7,000 on Class 6, ₹8,000 on Class 11, and ₹75,000 on reaching 18 years, totaling ₹1,01,000 in cash assistance.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹1,01,000 total cumulative financial assistance across 5 educational and age milestones',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 18,
      gender: 'Female',
      maxIncome: 100000,
      eligibleStates: ['Maharashtra'],
      eligibleOccupations: ['Student', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: ['Girl Child'],
    },
    requiredDocuments: ['Birth Certificate of Girl Child', 'Yellow or Orange Ration Card', 'Parents Aadhaar Card', 'Bank Passbook in Name of Girl Child'],
    applicationProcess: ['Submit application to local Anganwadi worker or Child Development Project Officer (CDPO).', 'Approval granted after document inspection.'],
    officialUrl: 'https://womenchild.maharashtra.gov.in/',
    helplineNumber: '022-22027050',
    tags: ['Maharashtra', 'Girl Child', 'DBT Grant', 'Lek Ladki', 'State Scheme'],
  },
  {
    title: 'Ramai Awas Yojana (Maharashtra)',
    slug: 'maharashtra-ramai-awas-yojana',
    categorySlug: 'housing-urban-development',
    ministry: 'Social Justice and Special Assistance Department, Government of Maharashtra',
    department: 'Social Welfare Directorate',
    schemeLevel: 'State',
    state: 'Maharashtra',
    shortDescription: 'Financial grant of ₹1,30,000 (rural) and ₹2,50,000 (urban) for pucca house construction for SC and Neo-Buddhist families.',
    description: 'Ramai Awas Yojana provides financial housing grants to Scheduled Caste (SC) and Neo-Buddhist homeless families in rural and urban Maharashtra who possess their own land or kutcha house to construct a quality pucca house with sanitation toilet facilities.',
    benefitType: 'Subsidy',
    financialBenefit: '₹1,30,000 housing construction subsidy in rural areas and ₹2,50,000 in urban areas',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 80,
      gender: 'All',
      maxIncome: 150000,
      eligibleStates: ['Maharashtra'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Unemployed', 'Other'],
      eligibleCategories: ['SC'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Caste Certificate (SC / Neo-Buddhist)', 'Land Ownership Proof / Gram Panchayat 8A', 'Income Certificate (< ₹1.5 Lakh)', 'Aadhaar Card', 'Bank Passbook'],
    applicationProcess: ['Apply online on sjsa.maharashtra.gov.in or submit form to Block Development Officer (BDO).', 'Subsidy disbursed in milestone installments upon geo-tagged photo verification.'],
    officialUrl: 'https://sjsa.maharashtra.gov.in/',
    helplineNumber: '1800-22-1450',
    tags: ['Maharashtra', 'Housing', 'SC Welfare', 'Pucca House', 'State Scheme'],
  },

  // ==========================================
  // 3. UTTAR PRADESH STATE SCHEMES
  // ==========================================
  {
    title: 'Mukhyamantri Kanya Sumangala Yojana (Uttar Pradesh)',
    slug: 'up-mukhyamantri-kanya-sumangala-yojana',
    categorySlug: 'women-child-development',
    ministry: 'Department of Women and Child Development, Government of Uttar Pradesh',
    department: 'Directorate of Women Welfare',
    schemeLevel: 'State',
    state: 'Uttar Pradesh',
    shortDescription: 'Milestone financial grant of ₹25,000 across 6 stages from birth to graduation for girl children in UP.',
    description: 'Mukhyamantri Kanya Sumangala Yojana delivers ₹25,000 in direct monetary assistance across 6 educational and developmental stages (birth vaccination, Class 1, Class 6, Class 9, Class 10/12, and Degree/Diploma admission) for girl children of UP with family income under ₹3 Lakh.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹25,000 cumulative direct bank transfer across 6 tiers from birth to higher education',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 25,
      gender: 'Female',
      maxIncome: 300000,
      eligibleStates: ['Uttar Pradesh'],
      eligibleOccupations: ['Student', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: ['Girl Child'],
    },
    requiredDocuments: ['UP Domicile Certificate', 'Girl Child Birth Certificate', 'Income Certificate (< ₹3 Lakh)', 'School / College Admission Proof', 'Bank Passbook'],
    applicationProcess: ['Register on mksy.up.gov.in portal.', 'Select girl milestone category.', 'Upload required stage certificates and track status online.'],
    officialUrl: 'https://mksy.up.gov.in/',
    helplineNumber: '181 / 1098',
    tags: ['Uttar Pradesh', 'Girl Child', 'Education DBT', 'Kanya Sumangala', 'State Scheme'],
  },
  {
    title: 'Mukhyamantri Abhyudaya Yojana (Uttar Pradesh)',
    slug: 'up-mukhyamantri-abhyudaya-yojana',
    categorySlug: 'education-skill-training',
    ministry: 'Social Welfare Department, Government of Uttar Pradesh',
    department: 'Directorate of Social Welfare',
    schemeLevel: 'State',
    state: 'Uttar Pradesh',
    shortDescription: 'Free expert coaching and tablet devices for UPSC CSE, UPPSC, NEET, JEE, and NDA/CDS exams.',
    description: 'Abhyudaya Yojana provides 100% free high-caliber classroom coaching, mentorship from serving IAS and IPS officers, virtual study materials, and free tablets for economically disadvantaged meritorious students in UP preparing for civil services and medical/engineering entrance exams.',
    benefitType: 'Skill Training',
    financialBenefit: 'Free coaching by top civil servants and educators + free tablet distribution for top performers',
    eligibilityCriteria: {
      minAge: 16,
      maxAge: 32,
      gender: 'All',
      maxIncome: 500000,
      eligibleStates: ['Uttar Pradesh'],
      eligibleOccupations: ['Student', 'Unemployed'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aadhaar Card', 'Educational Marksheets', 'UP Domicile Certificate', 'Income Certificate'],
    applicationProcess: ['Apply on abhyuday.up.gov.in.', 'Appear for state online entrance assessment.', 'Selected candidates get admission in divisional coaching centres.'],
    officialUrl: 'http://abhyuday.up.gov.in/',
    helplineNumber: '0522-2287234',
    tags: ['Uttar Pradesh', 'Free Coaching', 'UPSC', 'NEET JEE', 'Tablets', 'State Scheme'],
  },
  {
    title: 'UP Gopalak Yojana',
    slug: 'up-gopalak-yojana',
    categorySlug: 'agriculture-rural-development',
    ministry: 'Department of Animal Husbandry, Government of Uttar Pradesh',
    department: 'Directorate of Animal Husbandry',
    schemeLevel: 'State',
    state: 'Uttar Pradesh',
    shortDescription: 'Subsidized dairy farm loan up to ₹9,00,000 for setting up dairy units with 10-12 milch cows/buffaloes.',
    description: 'UP Gopalak Yojana provides bank loans up to ₹9 Lakh through public sector banks for purchasing 10 to 12 milch cattle, accompanied by state interest subvention assistance of ₹40,000 per year for 5 years (₹2,00,000 total subsidy) to boost white revolution and rural dairy self-employment in UP.',
    benefitType: 'Loan / Credit',
    financialBenefit: '₹9,00,000 bank loan + ₹2,00,000 state interest subsidy (₹40,000/year for 5 years)',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 55,
      gender: 'All',
      maxIncome: 100000,
      eligibleStates: ['Uttar Pradesh'],
      eligibleOccupations: ['Farmer', 'Self-Employed', 'Unemployed'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aadhaar Card', 'UP Domicile Certificate', 'Land / Cattle Shed Availability Proof', 'Veterinary Fitness Certificate for Cattle', 'Bank Passbook'],
    applicationProcess: ['Apply at the office of Chief Veterinary Officer (CVO) in district.', 'CVO reviews and sanctions proposal for bank loan disbursement.'],
    officialUrl: 'http://animalhusb.upsdc.gov.in/',
    helplineNumber: '1800-180-5141',
    tags: ['Uttar Pradesh', 'Dairy Farming', 'Animal Husbandry', 'Subsidized Loan', 'State Scheme'],
  },
  {
    title: 'UP One District One Product (ODOP) Margin Money Scheme',
    slug: 'up-odop-margin-money-scheme',
    categorySlug: 'business-msme-entrepreneurship',
    ministry: 'Department of MSME and Export Promotion, Government of Uttar Pradesh',
    department: 'Directorate of Industries',
    schemeLevel: 'State',
    state: 'Uttar Pradesh',
    shortDescription: 'Up to 25% project cost financial subsidy (up to ₹20 Lakh) for artisans and MSMEs producing indigenous district products.',
    description: 'Under UP ODOP Margin Money Scheme, entrepreneurs setting up manufacturing and service enterprises for notified indigenous district products (e.g., Banarasi silk, Bhadohi carpets, Moradabad brassware, Kannauj perfume, Agra leather) receive 10% to 25% non-refundable margin money subsidy.',
    benefitType: 'Subsidy',
    financialBenefit: 'Margin money capital subsidy up to 25% of total project cost (maximum ₹20,00,000 subsidy)',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 60,
      gender: 'All',
      maxIncome: 5000000,
      eligibleStates: ['Uttar Pradesh'],
      eligibleOccupations: ['Artisan / Craftsperson', 'Business Owner / MSME', 'Self-Employed'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aadhaar Card', 'Detailed Project Report (DPR)', 'UP Domicile Proof', 'Udyam Registration Certificate', 'Bank Account Details'],
    applicationProcess: ['Apply online on msme.up.gov.in or odopup.in.', 'District Level Task Force Committee (DLTFC) evaluates project.', 'Recommended applications routed to lending bank for capital subsidy.'],
    officialUrl: 'https://odopup.in/',
    helplineNumber: '1800-1800-888',
    tags: ['Uttar Pradesh', 'ODOP', 'MSME Subsidy', 'Artisans', 'Crafts', 'State Scheme'],
  },
  {
    title: 'UP Mukhyamantri Awas Yojana (Rural)',
    slug: 'up-mukhyamantri-awas-yojana-rural',
    categorySlug: 'housing-urban-development',
    ministry: 'Rural Development Department, Government of Uttar Pradesh',
    department: 'Rural Housing Mission UP',
    schemeLevel: 'State',
    state: 'Uttar Pradesh',
    shortDescription: '100% state-funded housing grant of ₹1,20,000 to ₹1,30,000 for vulnerable rural families left out of PMAY-G.',
    description: 'UP Mukhyamantri Awas Yojana (Gramin) provides ₹1.20 Lakh in plain districts and ₹1.30 Lakh in Naxal/Bundelkhand districts directly to disaster-affected, leprosy-affected, encephalitis-affected, and marginalized rural families excluded from SECC-2011 lists for constructing pucca homes.',
    benefitType: 'Subsidy',
    financialBenefit: '₹1,20,000 to ₹1,30,000 construction grant + 90 days MGNREGS wages + ₹12,000 Swachh Bharat toilet assistance',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 85,
      gender: 'All',
      maxIncome: 120000,
      eligibleStates: ['Uttar Pradesh'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aadhaar Card', 'Kutcha House Photo with Geotag', 'UP Domicile Certificate', 'Bank Account Passbook'],
    applicationProcess: ['Nominated via Gram Sabha open meeting.', 'Block Development Officer conducts physical verification.', 'Funds transferred in 3 installments based on foundation, lintel, and roof completion.'],
    officialUrl: 'http://rd.up.nic.in/',
    helplineNumber: '0522-2287234',
    tags: ['Uttar Pradesh', 'Rural Housing', 'Pucca House', 'State Scheme'],
  },

  // ==========================================
  // 4. TAMIL NADU STATE SCHEMES
  // ==========================================
  {
    title: 'Kalaignar Magalir Urimai Thogai Thittam',
    slug: 'tamil-nadu-kalaignar-magalir-urimai-thogai-thittam',
    categorySlug: 'women-child-development',
    ministry: 'Special Programme Implementation Department, Government of Tamil Nadu',
    department: 'Revenue and Disaster Management Department',
    schemeLevel: 'State',
    state: 'Tamil Nadu',
    shortDescription: 'Direct basic income grant of ₹1,000 per month (₹12,000/year) to eligible women heads of households in Tamil Nadu.',
    description: 'Kalaignar Magalir Urimai Thogai provides ₹1,000 every month directly into the Aadhaar-linked bank accounts of over 1.15 crore women heads of families across Tamil Nadu, acknowledging their unpaid domestic labour and fostering social equity.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹1,000 per month (₹12,000 annually) transferred on the 15th of every month',
    eligibilityCriteria: {
      minAge: 21,
      maxAge: 70,
      gender: 'Female',
      maxIncome: 250000,
      eligibleStates: ['Tamil Nadu'],
      eligibleOccupations: ['Self-Employed', 'Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Smart Ration Card (Family Card)', 'Aadhaar Card', 'Electricity Consumer Number (Consumption < 3600 units/yr)', 'Bank Passbook'],
    applicationProcess: ['Applications collected via special camp held at fair price ration shops.', 'Biometric authentication and verification by Special Field Inspector.'],
    officialUrl: 'https://kmut.tn.gov.in/',
    helplineNumber: '044-25619208',
    tags: ['Tamil Nadu', 'Women Basic Income', 'DBT', 'Magalir Urimai', 'State Scheme'],
  },
  {
    title: "Chief Minister's Comprehensive Health Insurance Scheme (CMCHIS)",
    slug: 'tamil-nadu-cmchis-health-insurance',
    categorySlug: 'health-wellness',
    ministry: 'Health and Family Welfare Department, Government of Tamil Nadu',
    department: 'Tamil Nadu Health Systems Project',
    schemeLevel: 'State',
    state: 'Tamil Nadu',
    shortDescription: 'Cashless healthcare cover up to ₹5,00,000 per family per year for 1,513 medical and surgical treatments in Tamil Nadu.',
    description: 'CMCHIS (Amma / Kalaignar Health Scheme) offers cashless hospitalization benefits up to ₹5,00,000 per family per year across 1,513 procedures, 52 diagnostic tests, and 8 high-end diagnostic surgeries in empaneled private and government hospitals in Tamil Nadu.',
    benefitType: 'Insurance',
    financialBenefit: 'Cashless hospital treatment up to ₹5,00,000 per family per year',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 100,
      gender: 'All',
      maxIncome: 120000,
      eligibleStates: ['Tamil Nadu'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Smart Ration Card', 'Aadhaar Card', 'Income Certificate issued by Revenue Authority (< ₹1.20 Lakh/yr)'],
    applicationProcess: ['Visit District Collectorate CMCHIS Kiosk.', 'Biometrics enrolled and Smart Card issued.', 'Show Smart Card at empaneled hospital helpdesk for cashless admission.'],
    officialUrl: 'https://www.cmchistn.com/',
    helplineNumber: '1800-425-3993',
    tags: ['Tamil Nadu', 'Healthcare', 'Cashless Hospital', 'CMCHIS', 'State Scheme'],
  },
  {
    title: 'Pudhumai Penn Scheme (Moovalur Ramamirtham Ammaiyar)',
    slug: 'tamil-nadu-pudhumai-penn-scheme',
    categorySlug: 'education-skill-training',
    ministry: 'Social Welfare and Women Empowerment Department, Government of Tamil Nadu',
    department: 'Directorate of Social Welfare',
    schemeLevel: 'State',
    state: 'Tamil Nadu',
    shortDescription: 'Monthly financial assistance of ₹1,000 until completion of undergraduate degree/diploma for girls from government schools.',
    description: 'Pudhumai Penn Scheme provides ₹1,000 per month deposited directly into bank accounts of girl students who studied Classes 6 to 12 in Tamil Nadu government schools until they complete their undergraduate degree, ITI, or polytechnic diploma course.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹1,000 per month (₹12,000/year) disbursed directly during entire collegiate graduation duration',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 25,
      gender: 'Female',
      maxIncome: 600000,
      eligibleStates: ['Tamil Nadu'],
      eligibleOccupations: ['Student'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: ['Girl Child'],
    },
    requiredDocuments: ['Proof of studying Classes 6-12 in TN Govt School (EMIS Number)', 'College ID & Admission Letter', 'Aadhaar Card', 'Bank Passbook'],
    applicationProcess: ['Apply through designated College Nodal Officer on pudhumaipenn.tn.gov.in.', 'College validates schooling records and submits for monthly DBT.'],
    officialUrl: 'https://pudhumaipenn.tn.gov.in/',
    helplineNumber: '044-24351885',
    tags: ['Tamil Nadu', 'Girl Education', 'Higher Education Stipend', 'Pudhumai Penn', 'State Scheme'],
  },
  {
    title: 'Uzhavar Pathukappu Thittam (Tamil Nadu Farmers Social Security)',
    slug: 'tamil-nadu-uzhavar-pathukappu-thittam',
    categorySlug: 'agriculture-rural-development',
    ministry: 'Revenue and Disaster Management Department, Government of Tamil Nadu',
    department: 'Commissionerate of Revenue Administration',
    schemeLevel: 'State',
    state: 'Tamil Nadu',
    shortDescription: 'Comprehensive social security covering accidental relief (₹1 Lakh), old age pension (₹1,000/mo), and marriage grants for farm workers.',
    description: 'Chief Minister Uzhavar Pathukappu Thittam provides end-to-end statutory social security for farmers, agricultural labourers, and tenant farmers in Tamil Nadu, including ₹1,00,000 accidental death relief, monthly old age pensions, maternal assistance, and children educational scholarships.',
    benefitType: 'In-Kind Support',
    financialBenefit: '₹1,00,000 accidental relief + ₹1,000/month old age pension + ₹10,000 marriage grant + education grants',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 65,
      gender: 'All',
      maxIncome: 120000,
      eligibleStates: ['Tamil Nadu'],
      eligibleOccupations: ['Farmer'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Uzhavar Pathukappu Thittam Member Card', 'Aadhaar Card', 'Land/Tenancy Certificate from Village Administrative Officer (VAO)'],
    applicationProcess: ['Register with Taluk Special Tahsildar (Uzhavar Pathukappu Thittam).', 'Identity card issued for claiming social security benefits.'],
    officialUrl: 'https://www.tn.gov.in/scheme/data_view/6858',
    helplineNumber: '044-28592230',
    tags: ['Tamil Nadu', 'Farmers Pension', 'Accident Relief', 'Agrarian Security', 'State Scheme'],
  },

  // ==========================================
  // 5. KARNATAKA STATE SCHEMES
  // ==========================================
  {
    title: 'Gruha Lakshmi Scheme (Karnataka)',
    slug: 'karnataka-gruha-lakshmi-scheme',
    categorySlug: 'women-child-development',
    ministry: 'Women and Child Development Department, Government of Karnataka',
    department: 'Directorate of Women and Child Development',
    schemeLevel: 'State',
    state: 'Karnataka',
    shortDescription: 'Financial assistance of ₹2,000 per month (₹24,000/year) directly transferred to female heads of families in Karnataka.',
    description: 'Gruha Lakshmi Scheme is one of the 5 Guarantees of the Karnataka Government, transferring ₹2,000 every month directly into the Aadhaar-seeded bank accounts of woman heads of household listed on Antyodaya, BPL, and APL ration cards.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹2,000 per month (₹24,000 per year) direct cash transfer',
    eligibilityCriteria: {
      minAge: 19,
      maxAge: 80,
      gender: 'Female',
      maxIncome: 800000,
      eligibleStates: ['Karnataka'],
      eligibleOccupations: ['Self-Employed', 'Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Ration Card (APL / BPL / Antyodaya)', 'Aadhaar Card of Woman Head & Spouse', 'Aadhaar-seeded Bank Passbook'],
    applicationProcess: ['Apply at Grama One, Karnataka One, or Bangalore One centres.', 'Biometric verification links applicant account for monthly DBT.'],
    officialUrl: 'https://sevasindhugs.karnataka.gov.in/',
    helplineNumber: '1902 / 080-22279970',
    tags: ['Karnataka', 'Women Guarantee', 'Gruha Lakshmi', 'Monthly Cash', 'State Scheme'],
  },
  {
    title: 'Yuva Nidhi Scheme (Karnataka)',
    slug: 'karnataka-yuva-nidhi-scheme',
    categorySlug: 'education-skill-training',
    ministry: 'Skill Development, Entrepreneurship and Livelihood Department, Government of Karnataka',
    department: 'Department of Employment and Training',
    schemeLevel: 'State',
    state: 'Karnataka',
    shortDescription: 'Unemployment financial allowance of ₹3,000/month for graduates and ₹1,500/month for diploma holders for up to 2 years.',
    description: 'Yuva Nidhi provides financial cushioning to educated unemployed youth in Karnataka who graduated in the academic year 2022-23 onwards and have remained unemployed for 6 months after graduation, assisting them during career job searches.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹3,000 per month for Degree Graduates and ₹1,500 per month for Diploma Holders for up to 24 months',
    eligibilityCriteria: {
      minAge: 20,
      maxAge: 30,
      gender: 'All',
      maxIncome: 500000,
      eligibleStates: ['Karnataka'],
      eligibleOccupations: ['Unemployed', 'Student'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Degree / Diploma Certificate', 'Karnataka Domicile Proof (Min 6 years study in Karnataka)', 'Aadhaar Card', 'Unemployment Self-Declaration'],
    applicationProcess: ['Register on Seva Sindhu portal (sevasindhugs.karnataka.gov.in).', 'Submit degree details and monthly self-declaration of unemployment.'],
    officialUrl: 'https://sevasindhugs.karnataka.gov.in/',
    helplineNumber: '1800-599-9918',
    tags: ['Karnataka', 'Unemployment Allowance', 'Yuva Nidhi', 'Youth Support', 'State Scheme'],
  },
  {
    title: 'Gruha Jyothi Scheme (Karnataka)',
    slug: 'karnataka-gruha-jyothi-scheme',
    categorySlug: 'housing-urban-development',
    ministry: 'Energy Department, Government of Karnataka',
    department: 'Karnataka Electricity Regulatory Commission (ESCOMs)',
    schemeLevel: 'State',
    state: 'Karnataka',
    shortDescription: 'Free domestic electricity up to 200 units per month for all residential households in Karnataka.',
    description: 'Gruha Jyothi is a landmark welfare guarantee providing up to 200 units of free power every month to domestic electricity consumers in Karnataka, calculated based on the household average monthly consumption plus a 10% allowance.',
    benefitType: 'Subsidy',
    financialBenefit: '100% electricity bill waiver up to 200 units per month (saving ₹1,000 to ₹1,800/month per family)',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 100,
      gender: 'All',
      maxIncome: 10000000,
      eligibleStates: ['Karnataka'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Employed / Salaried', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Electricity Bill with Account ID', 'Aadhaar Card', 'Tenant / Owner Tenancy Proof'],
    applicationProcess: ['Register online on Seva Sindhu Gruha Jyothi portal.', 'Link Account ID with Aadhaar number.', 'Zero bill issued for consumption under quota.'],
    officialUrl: 'https://sevasindhugs.karnataka.gov.in/',
    helplineNumber: '1912',
    tags: ['Karnataka', 'Free Electricity', 'Gruha Jyothi', 'Energy Subsidy', 'State Scheme'],
  },
  {
    title: 'Raitha Siri Scheme (Karnataka)',
    slug: 'karnataka-raitha-siri-scheme',
    categorySlug: 'agriculture-rural-development',
    ministry: 'Department of Agriculture, Government of Karnataka',
    department: 'Directorate of Agriculture',
    schemeLevel: 'State',
    state: 'Karnataka',
    shortDescription: 'Cash incentive of ₹10,000 per hectare directly credited to bank accounts of minor millet farmers.',
    description: 'Raitha Siri encourages cultivation of nutritious minor millets (Siri Dhanya like Foxtail, Little, Kodo, Barnyard, and Proso millet) in drought-prone areas of Karnataka by transferring ₹10,000 per hectare directly into farmers bank accounts.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹10,000 per hectare (up to maximum 2 hectares: ₹20,000) direct cash incentive',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 85,
      gender: 'All',
      maxIncome: 1500000,
      eligibleStates: ['Karnataka'],
      eligibleOccupations: ['Farmer'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['FRUITS Farmer Registration ID', 'Pahani / RTC Land Record with Millet Crop Sowing Entry', 'Aadhaar Card', 'Bank Passbook'],
    applicationProcess: ['Enroll in FRUITS portal (fruits.karnataka.gov.in).', 'Crop survey confirms minor millet cultivation.', 'Incentive directly transferred via DBT.'],
    officialUrl: 'https://raitamitra.karnataka.gov.in/',
    helplineNumber: '080-22212834',
    tags: ['Karnataka', 'Millets', 'Siri Dhanya', 'Farmer Incentive', 'State Scheme'],
  },

  // ==========================================
  // 6. RAJASTHAN STATE SCHEMES
  // ==========================================
  {
    title: 'Mukhyamantri Chiranjeevi Swasthya Bima Yojana (Rajasthan)',
    slug: 'rajasthan-chiranjeevi-swasthya-bima-yojana',
    categorySlug: 'health-wellness',
    ministry: 'Medical, Health and Family Welfare Department, Government of Rajasthan',
    department: 'Rajasthan State Health Society',
    schemeLevel: 'State',
    state: 'Rajasthan',
    shortDescription: 'Cashless medical treatment cover up to ₹25,00,000 per family per year across 1,798 packages in Rajasthan.',
    description: 'Chiranjeevi Swasthya Bima Yojana provides unprecedented cashless medical insurance coverage up to ₹25 Lakh per family per year, along with ₹10 Lakh accidental insurance, for inpatient hospitalization across empaneled government and private hospitals in Rajasthan.',
    benefitType: 'Insurance',
    financialBenefit: 'Cashless health insurance coverage up to ₹25,00,000 per family per year + ₹10,00,000 accident cover',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 100,
      gender: 'All',
      maxIncome: 10000000,
      eligibleStates: ['Rajasthan'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Employed / Salaried', 'Unemployed', 'Student', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Jan Aadhaar Card', 'Aadhaar Card', 'Rajasthan Domicile Proof'],
    applicationProcess: ['Register with Jan Aadhaar Card on chiranjeevi.rajasthan.gov.in or through e-Mitra kiosk.', 'Present Jan Aadhaar Card at hospital helpdesk for cashless admission.'],
    officialUrl: 'https://chiranjeevi.rajasthan.gov.in/',
    helplineNumber: '181',
    tags: ['Rajasthan', 'Healthcare', 'Cashless Hospital', '25 Lakh Cover', 'State Scheme'],
  },
  {
    title: 'Indira Gandhi Shehri Rozgar Guarantee Yojana (Rajasthan)',
    slug: 'rajasthan-indira-gandhi-shehri-rozgar-guarantee',
    categorySlug: 'housing-urban-development',
    ministry: 'Local Self Government Department, Government of Rajasthan',
    department: 'Directorate of Local Bodies',
    schemeLevel: 'State',
    state: 'Rajasthan',
    shortDescription: '125 days of guaranteed urban wage employment per year for urban households in Rajasthan.',
    description: 'Modeled on rural MGNREGS, this scheme guarantees 125 days of paid employment annually to adults living in urban municipal areas of Rajasthan for tree plantation, heritage maintenance, desilting, sanitation, and municipal public works.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: 'Guaranteed statutory wages for 125 days (approx ₹259 to ₹333 per day directly credited to bank account)',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 60,
      gender: 'All',
      maxIncome: 300000,
      eligibleStates: ['Rajasthan'],
      eligibleOccupations: ['Unemployed', 'Street Vendor', 'Artisan / Craftsperson', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Jan Aadhaar Card', 'Aadhaar Card', 'Urban Local Body Domicile Proof'],
    applicationProcess: ['Register Jan Aadhaar Card on irgyurban.rajasthan.gov.in or at Urban Local Body ward office.', 'Job card issued within 15 days.'],
    officialUrl: 'https://irgyurban.rajasthan.gov.in/',
    helplineNumber: '181',
    tags: ['Rajasthan', 'Urban Employment', 'Job Guarantee', 'Wage Labour', 'State Scheme'],
  },
  {
    title: 'Mukhyamantri Anupriti Coaching Yojana (Rajasthan)',
    slug: 'rajasthan-mukhyamantri-anupriti-coaching-yojana',
    categorySlug: 'education-skill-training',
    ministry: 'Social Justice and Empowerment Department, Government of Rajasthan',
    department: 'Directorate of Social Justice',
    schemeLevel: 'State',
    state: 'Rajasthan',
    shortDescription: 'Free competitive examination coaching and ₹40,000 annual residential allowance for underprivileged students.',
    description: 'Anupriti Coaching Yojana sponsors 30,000 meritorious students belonging to SC, ST, OBC, MBC, EWS, and minority communities annually for professional entrance exams (IAS, RAS, REET, NEET, JEE, CLAT) at top coaching institutes, providing free tuition plus ₹40,000 hostel allowance.',
    benefitType: 'Skill Training',
    financialBenefit: '100% paid coaching fees at premier institutes + ₹40,000/year living and boarding allowance',
    eligibilityCriteria: {
      minAge: 16,
      maxAge: 30,
      gender: 'All',
      maxIncome: 800000,
      eligibleStates: ['Rajasthan'],
      eligibleOccupations: ['Student', 'Unemployed'],
      eligibleCategories: ['SC', 'ST', 'OBC', 'EWS'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Jan Aadhaar Card', '10th / 12th / Graduation Marksheet', 'Caste Certificate', 'Income Certificate (< ₹8 Lakh)'],
    applicationProcess: ['Apply on SJMS Portal (sje.rajasthan.gov.in).', 'Select exam stream and preferred coaching institute.', 'Merit lists published based on Class 10/12 marks.'],
    officialUrl: 'https://sje.rajasthan.gov.in/',
    helplineNumber: '1800-180-6127',
    tags: ['Rajasthan', 'Free Coaching', 'Hostel Stipend', 'Anupriti', 'State Scheme'],
  },

  // ==========================================
  // 7. DELHI NCT SCHEMES
  // ==========================================
  {
    title: 'Delhi Free Lifeline Water Scheme',
    slug: 'delhi-free-lifeline-water-scheme',
    categorySlug: 'housing-urban-development',
    ministry: 'Urban Development Department, Government of NCT of Delhi',
    department: 'Delhi Jal Board (DJB)',
    schemeLevel: 'State',
    state: 'Delhi',
    shortDescription: 'Zero water bill for households consuming up to 20,000 litres of clean piped water per month in Delhi.',
    description: 'Delhi Free Lifeline Water Scheme provides up to 20,000 litres (20 kilolitres) of clean domestic water free of charge every month to all households in the National Capital Territory of Delhi equipped with working domestic functional water meters.',
    benefitType: 'Subsidy',
    financialBenefit: '100% waiver of water consumption charges, sewerage charges, and service charges up to 20,000 litres/month',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 100,
      gender: 'All',
      maxIncome: 10000000,
      eligibleStates: ['Delhi'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Employed / Salaried', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Delhi Jal Board (DJB) K No. / Consumer Water Connection Details', 'Aadhaar Card', 'Active Working Domestic Meter'],
    applicationProcess: ['Automatic billing rebate applied to DJB monthly consumer water bill for consumption under 20 kL.'],
    officialUrl: 'http://delhijalboard.nic.in/',
    helplineNumber: '1916 / 011-23524976',
    tags: ['Delhi', 'Free Water', 'Urban Utility', 'Lifeline Water', 'State Scheme'],
  },
  {
    title: 'Jai Bhim Mukhyamantri Pratibha Vikas Yojana (Delhi)',
    slug: 'delhi-jai-bhim-mukhyamantri-pratibha-vikas-yojana',
    categorySlug: 'education-skill-training',
    ministry: 'Department for Welfare of SC/ST/OBC, Government of NCT of Delhi',
    department: 'Directorate of Welfare of SC/ST',
    schemeLevel: 'State',
    state: 'Delhi',
    shortDescription: 'Free competitive exam coaching and ₹2,500 monthly stipend for SC, ST, OBC, and EWS students in Delhi.',
    description: 'This scheme sponsors 100% coaching fees for civil services (UPSC), banking, SSC, judicial services, engineering (JEE), and medical (NEET) entrance exams at empaneled private coaching institutes, along with a ₹2,500/month travel and living stipend for Delhi students.',
    benefitType: 'Skill Training',
    financialBenefit: '100% full coaching tuition fees covered + ₹2,500/month living stipend for up to 12 months',
    eligibilityCriteria: {
      minAge: 16,
      maxAge: 32,
      gender: 'All',
      maxIncome: 800000,
      eligibleStates: ['Delhi'],
      eligibleOccupations: ['Student', 'Unemployed'],
      eligibleCategories: ['SC', 'ST', 'OBC', 'EWS'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Delhi Domicile Certificate / Delhi School Passout Certificate', 'Caste Certificate (SC/ST/OBC/EWS)', 'Income Certificate (< ₹8 Lakh)', 'Aadhaar Card'],
    applicationProcess: ['Apply directly at empaneled coaching institute or through welfare dept portal.', 'Institute verifies documents and submits for government sponsorship.'],
    officialUrl: 'https://scstwelfare.delhi.gov.in/',
    helplineNumber: '011-23379511',
    tags: ['Delhi', 'Free Coaching', 'Monthly Stipend', 'SC ST Welfare', 'State Scheme'],
  },
  {
    title: 'Delhi Electric Vehicle (EV) Subsidy Policy',
    slug: 'delhi-electric-vehicle-ev-subsidy-policy',
    categorySlug: 'science-it-employment',
    ministry: 'Transport Department, Government of NCT of Delhi',
    department: 'Delhi Electric Vehicle Cell (DEVC)',
    schemeLevel: 'State',
    state: 'Delhi',
    shortDescription: 'Direct purchase subsidy up to ₹30,000 for 2-wheelers and ₹1,50,000 for 4-wheelers + 100% road tax exemption.',
    description: 'Delhi EV Policy provides generous financial incentives to accelerate electric vehicle adoption, offering ₹5,000 per kWh battery capacity (up to ₹30,000) for electric two-wheelers and auto-rickshaws, and up to ₹1,50,000 for electric four-wheelers, plus 100% waiver on road tax and registration fees.',
    benefitType: 'Subsidy',
    financialBenefit: 'Purchase subsidy up to ₹30,000 (two-wheelers) / ₹1,50,000 (four-wheelers) + 100% road tax and registration waiver',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 85,
      gender: 'All',
      maxIncome: 10000000,
      eligibleStates: ['Delhi'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Employed / Salaried', 'Business Owner / MSME', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aadhaar Card with Delhi Address', 'Vehicle Invoice from Authorized Delhi EV Dealer', 'Vehicle Registration Certificate (RC)', 'Cancelled Bank Cheque'],
    applicationProcess: ['EV dealer files subsidy claim on Delhi EV portal at point of purchase.', 'Subsidy directly credited to buyer bank account within 7 to 15 days.'],
    officialUrl: 'https://ev.delhi.gov.in/',
    helplineNumber: '011-23992200',
    tags: ['Delhi', 'EV Subsidy', 'Clean Energy', 'Green Mobility', 'State Scheme'],
  },

  // ==========================================
  // 8. WEST BENGAL STATE SCHEMES
  // ==========================================
  {
    title: 'Lakshmir Bhandar Scheme (West Bengal)',
    slug: 'west-bengal-lakshmir-bhandar-scheme',
    categorySlug: 'women-child-development',
    ministry: 'Department of Women and Child Development and Social Welfare, Government of West Bengal',
    department: 'Directorate of Social Welfare',
    schemeLevel: 'State',
    state: 'West Bengal',
    shortDescription: 'Monthly financial assistance of ₹1,000 (General) and ₹1,200 (SC/ST) directly to female heads of family in West Bengal.',
    description: 'Lakshmir Bhandar provides monthly financial assistance of ₹1,000 to women heads of general category households and ₹1,200 to SC/ST households aged 25-60 years across West Bengal directly into their Aadhaar-linked bank accounts.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹1,000/month (General) and ₹1,200/month (SC/ST) direct bank transfer',
    eligibilityCriteria: {
      minAge: 25,
      maxAge: 60,
      gender: 'Female',
      maxIncome: 500000,
      eligibleStates: ['West Bengal'],
      eligibleOccupations: ['Self-Employed', 'Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Swasthya Sathi Card', 'Aadhaar Card', 'Caste Certificate (if SC/ST for higher benefit)', 'Bank Passbook'],
    applicationProcess: ['Collect and submit application form at Duare Sarkar camps.', 'Verification conducted by Block Development Officer (BDO).'],
    officialUrl: 'https://wb.gov.in/',
    helplineNumber: '033-22143526',
    tags: ['West Bengal', 'Women Assistance', 'Lakshmir Bhandar', 'Duare Sarkar', 'State Scheme'],
  },
  {
    title: 'Swasthya Sathi Scheme (West Bengal)',
    slug: 'west-bengal-swasthya-sathi-scheme',
    categorySlug: 'health-wellness',
    ministry: 'Department of Health and Family Welfare, Government of West Bengal',
    department: 'Swasthya Sathi Samiti',
    schemeLevel: 'State',
    state: 'West Bengal',
    shortDescription: 'Universal cashless health coverage up to ₹5,00,000 per family per year with smart card issued to female head of household.',
    description: 'Swasthya Sathi provides universal cashless secondary and tertiary healthcare coverage up to ₹5 Lakh per family per year across 2,000+ medical packages, empowering women by issuing the smart insurance card exclusively in the name of the seniormost female family head.',
    benefitType: 'Insurance',
    financialBenefit: 'Cashless medical and surgical cover up to ₹5,00,000 per family per year',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 100,
      gender: 'All',
      maxIncome: 10000000,
      eligibleStates: ['West Bengal'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Employed / Salaried', 'Unemployed', 'Student', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aadhaar Card', 'Ration Card', 'West Bengal Domicile Proof'],
    applicationProcess: ['Enroll at Duare Sarkar outreach camps or BDO office.', 'Biometric capture and immediate photo smart card issuance.'],
    officialUrl: 'https://swasthyasathi.gov.in/',
    helplineNumber: '1800-345-5384',
    tags: ['West Bengal', 'Healthcare', 'Cashless Hospital', 'Swasthya Sathi', 'State Scheme'],
  },
  {
    title: 'Kanyashree Prakalpa (West Bengal)',
    slug: 'west-bengal-kanyashree-prakalpa',
    categorySlug: 'education-skill-training',
    ministry: 'Department of Women and Child Development and Social Welfare, Government of West Bengal',
    department: 'Directorate of Child Rights',
    schemeLevel: 'State',
    state: 'West Bengal',
    shortDescription: 'Annual scholarship of ₹1,000 (K1) and one-time higher education grant of ₹25,000 (K2) to prevent child marriage and educate girls.',
    description: 'UN-award-winning Kanyashree Prakalpa improves the life and status of adolescent girls in West Bengal by providing an annual scholarship of ₹1,000 for girls aged 13-18 in Classes 8-12 (K1) and a one-time grant of ₹25,000 upon reaching 18 years if unmarried and continuing education (K2).',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹1,000 annual scholarship (K1) + ₹25,000 one-time grant (K2) upon reaching 18 years unmarried',
    eligibilityCriteria: {
      minAge: 13,
      maxAge: 19,
      gender: 'Female',
      maxIncome: 120000,
      eligibleStates: ['West Bengal'],
      eligibleOccupations: ['Student'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: ['Girl Child'],
    },
    requiredDocuments: ['School / College Enrollment Certificate', 'Unmarried Declaration Certificate', 'Birth Certificate', 'Bank Passbook in Girl Name'],
    applicationProcess: ['Form provided free at student school/college.', 'Institution head verifies and uploads to Kanyashree Portal.'],
    officialUrl: 'https://wbkanyashree.gov.in/',
    helplineNumber: '033-23373840',
    tags: ['West Bengal', 'Girl Education', 'Kanyashree', 'UN Award', 'State Scheme'],
  },
  {
    title: 'Krishak Bandhu (Natun) Scheme (West Bengal)',
    slug: 'west-bengal-krishak-bandhu-natun-scheme',
    categorySlug: 'agriculture-rural-development',
    ministry: 'Department of Agriculture, Government of West Bengal',
    department: 'Directorate of Agriculture',
    schemeLevel: 'State',
    state: 'West Bengal',
    shortDescription: 'Income support up to ₹10,000/year (₹4,000 minimum) + ₹2 Lakh death assurance for farm families in West Bengal.',
    description: 'Krishak Bandhu provides agricultural financial assistance up to ₹10,000 per year (minimum ₹4,000/year even for landless farm workers) in two seasonal installments (Kharif and Rabi), along with a ₹2,00,000 death compensation grant for farmer families in event of sudden demise.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹4,000 to ₹10,000 per year farm assistance + ₹2,00,000 death compensation assurance',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 60,
      gender: 'All',
      maxIncome: 2000000,
      eligibleStates: ['West Bengal'],
      eligibleOccupations: ['Farmer'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['ROR / Land Record (Khatian / Parcha)', 'Aadhaar Card', 'Voter Card', 'Bank Passbook'],
    applicationProcess: ['Apply at Duare Sarkar camp or Assistant Director of Agriculture (ADA) block office.', 'DBT credited directly to bank account twice a year.'],
    officialUrl: 'https://krishakbandhu.wb.gov.in/',
    helplineNumber: '033-22258999',
    tags: ['West Bengal', 'Farmer Support', 'Death Benefit', 'Krishak Bandhu', 'State Scheme'],
  },

  // ==========================================
  // 9. MADHYA PRADESH STATE SCHEMES
  // ==========================================
  {
    title: 'Mukhyamantri Ladli Behna Yojana (Madhya Pradesh)',
    slug: 'mp-mukhyamantri-ladli-behna-yojana',
    categorySlug: 'women-child-development',
    ministry: 'Women and Child Development Department, Government of Madhya Pradesh',
    department: 'Directorate of Women and Child Development',
    schemeLevel: 'State',
    state: 'Madhya Pradesh',
    shortDescription: 'Monthly direct cash transfer of ₹1,250 per month (₹15,000/year) to women aged 21-60 in Madhya Pradesh.',
    description: 'Ladli Behna Yojana provides monthly financial empowerment assistance of ₹1,250 transferred on the 10th of every month into the Aadhaar-linked DBT bank accounts of married women aged 21-60 years residing in Madhya Pradesh with household income under ₹2.5 Lakh.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹1,250 per month (₹15,000 annually) transferred directly through DBT',
    eligibilityCriteria: {
      minAge: 21,
      maxAge: 60,
      gender: 'Female',
      maxIncome: 250000,
      eligibleStates: ['Madhya Pradesh'],
      eligibleOccupations: ['Self-Employed', 'Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Samagra Family ID and Member ID', 'Aadhaar Card linked with Bank Account', 'Mobile Number linked to Aadhaar'],
    applicationProcess: ['Fill application at Gram Panchayat or Ward office camp.', 'e-KYC verified through Aadhaar biometric or OTP on cmladlibahna.mp.gov.in.'],
    officialUrl: 'https://cmladlibahna.mp.gov.in/',
    helplineNumber: '0755-2700800',
    tags: ['Madhya Pradesh', 'Women Empowerment', 'Ladli Behna', 'Monthly Cash', 'State Scheme'],
  },
  {
    title: 'Mukhyamantri Seekho Kamao Yojana (MMSKY)',
    slug: 'mp-mukhyamantri-seekho-kamao-yojana',
    categorySlug: 'education-skill-training',
    ministry: 'Technical Education, Skill Development and Employment Department, Government of Madhya Pradesh',
    department: 'MP State Skill Development Mission',
    schemeLevel: 'State',
    state: 'Madhya Pradesh',
    shortDescription: 'On-the-job industrial apprenticeship with ₹8,000 to ₹10,000 monthly government stipend for MP youth.',
    description: 'MMSKY pairs young job-seekers of MP aged 18-29 years with leading industrial, technical, and service establishments for 1-year on-the-job skill training, with the MP government funding 75% of monthly stipends (₹8,000 for 12th pass, ₹8,500 for ITI, ₹9,000 for Diploma, and ₹10,000 for Degree).',
    benefitType: 'Skill Training',
    financialBenefit: 'Monthly stipend of ₹8,000 to ₹10,000 transferred directly through DBT during training',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 29,
      gender: 'All',
      maxIncome: 600000,
      eligibleStates: ['Madhya Pradesh'],
      eligibleOccupations: ['Student', 'Unemployed'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Samagra ID', 'Educational Marksheet (12th / ITI / Diploma / Degree)', 'Aadhaar Card', 'DBT-enabled Bank Passbook'],
    applicationProcess: ['Register on mmsky.mp.gov.in portal.', 'Select industrial training trade and company.', 'Sign apprenticeship contract online and start training.'],
    officialUrl: 'https://mmsky.mp.gov.in/',
    helplineNumber: '0755-2525200',
    tags: ['Madhya Pradesh', 'Skill Stipend', 'Apprenticeship', 'Youth Jobs', 'State Scheme'],
  },
  {
    title: 'Mukhyamantri Kisan Kalyan Yojana (Madhya Pradesh)',
    slug: 'mp-mukhyamantri-kisan-kalyan-yojana',
    categorySlug: 'agriculture-rural-development',
    ministry: 'Farmer Welfare and Agriculture Development Department, Government of Madhya Pradesh',
    department: 'Directorate of Farmer Welfare',
    schemeLevel: 'State',
    state: 'Madhya Pradesh',
    shortDescription: 'State supplemental cash grant of ₹6,000 per year (total ₹12,000/year with PM-KISAN) for MP farmers.',
    description: 'Mukhyamantri Kisan Kalyan Yojana provides an additional financial assistance of ₹6,000 per year in two equal installments of ₹3,000 to all PM-KISAN beneficiary farmers in MP, doubling their annual agrarian support to ₹12,000.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹6,000 per year in two installments of ₹3,000 directly through DBT (total ₹12,000/yr with PM-KISAN)',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 85,
      gender: 'All',
      maxIncome: 2500000,
      eligibleStates: ['Madhya Pradesh'],
      eligibleOccupations: ['Farmer'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Samagra ID', 'Aadhaar Card', 'Land Revenue Khasra Details', 'PM-KISAN Registration Number'],
    applicationProcess: ['Patwari registers eligible farmers on SAARA portal (saara.mp.gov.in).', 'Direct Aadhaar DBT transfer upon verification.'],
    officialUrl: 'https://saara.mp.gov.in/',
    helplineNumber: '181',
    tags: ['Madhya Pradesh', 'Farmer Support', 'Kisan Kalyan', 'DBT', 'State Scheme'],
  },

  // ==========================================
  // 10. BIHAR STATE SCHEMES
  // ==========================================
  {
    title: 'Mukhyamantri Kanya Utthan Yojana (Bihar)',
    slug: 'bihar-mukhyamantri-kanya-utthan-yojana',
    categorySlug: 'women-child-development',
    ministry: 'Social Welfare Department and Education Department, Government of Bihar',
    department: 'Directorate of Social Welfare',
    schemeLevel: 'State',
    state: 'Bihar',
    shortDescription: 'Total financial assistance of ₹54,100 from birth up to graduation (₹50,000 on college degree) for Bihar girls.',
    description: 'Mukhyamantri Kanya Utthan Yojana is a transformative girl child scheme in Bihar delivering milestone cash grants: ₹2,000 on birth, ₹1,000 on Aadhaar linking, ₹2,000 on vaccination, ₹10,000 on 10th pass, ₹25,000 on unmarried 12th pass, and ₹50,000 on passing graduation degree.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: 'Up to ₹54,100 milestone cash assistance, including ₹50,000 direct bank transfer on passing Graduation degree',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 28,
      gender: 'Female',
      maxIncome: 500000,
      eligibleStates: ['Bihar'],
      eligibleOccupations: ['Student', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: ['Girl Child'],
    },
    requiredDocuments: ['Bihar Domicile Certificate', 'Graduation / 12th Passing Marksheet', 'Aadhaar Card', 'Bank Account in Student Name in Bihar'],
    applicationProcess: ['Apply on medhasoft.bih.nic.in portal.', 'College verifies registration and university marksheet.', 'Amount disbursed directly via PFMS.'],
    officialUrl: 'https://medhasoft.bih.nic.in/',
    helplineNumber: '0612-2215323',
    tags: ['Bihar', 'Girl Graduation', '50,000 Grant', 'Kanya Utthan', 'State Scheme'],
  },
  {
    title: 'Bihar Student Credit Card Scheme (BSCCS)',
    slug: 'bihar-student-credit-card-scheme',
    categorySlug: 'education-skill-training',
    ministry: 'Education Department, Government of Bihar',
    department: 'Bihar State Higher Education Council',
    schemeLevel: 'State',
    state: 'Bihar',
    shortDescription: 'Collateral-free education loan up to ₹4,00,000 at 1% interest for girls/transgender and 4% for boys for higher studies.',
    description: 'Part of Bihar "7 Nischay", this scheme provides collateral-free education loans up to ₹4 Lakh through the Bihar State Educational Finance Corporation for pursuing higher professional education (B.Tech, MBBS, MBA, BCA, Diploma) with state government guarantee.',
    benefitType: 'Loan / Credit',
    financialBenefit: 'Collateral-free loan up to ₹4,00,000 at highly subsidized 1% simple interest for women/disabled/transgender and 4% for boys',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 25,
      gender: 'All',
      maxIncome: 800000,
      eligibleStates: ['Bihar'],
      eligibleOccupations: ['Student'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['10th and 12th Marksheets', 'College Admission Offer Letter and Fee Structure', 'Bihar Domicile Certificate', 'Aadhaar Card of Student & Co-Applicant'],
    applicationProcess: ['Apply on 7 Nischay portal (mnssby.bihar.gov.in).', 'Visit District Registration and Counselling Centre (DRCC) for document verification.'],
    officialUrl: 'https://www.7nishchay-yuvaupmission.bihar.gov.in/',
    helplineNumber: '1800-345-6444',
    tags: ['Bihar', 'Education Loan', 'Student Credit Card', 'Higher Education', 'State Scheme'],
  },
  {
    title: 'Mukhyamantri Udyami Yojana (Bihar)',
    slug: 'bihar-mukhyamantri-udyami-yojana',
    categorySlug: 'business-msme-entrepreneurship',
    ministry: 'Industries Department, Government of Bihar',
    department: 'Directorate of Technical Development',
    schemeLevel: 'State',
    state: 'Bihar',
    shortDescription: '₹10,00,000 financial support (₹5 Lakh 100% grant + ₹5 Lakh interest-free loan) for setting up micro manufacturing units in Bihar.',
    description: 'Mukhyamantri Udyami Yojana (SC/ST/EBC/Women/Yuva) offers ₹10 Lakh financial package to promote entrepreneurship in Bihar: ₹5,00,000 as a direct non-refundable grant and ₹5,00,000 as an interest-free (or 1% for general youth) loan repayable in 84 easy monthly installments.',
    benefitType: 'Subsidy',
    financialBenefit: '₹10,00,000 total package (₹5,00,000 direct grant subsidy + ₹5,00,000 interest-free loan) + ₹25,000 training allowance',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 50,
      gender: 'All',
      maxIncome: 1500000,
      eligibleStates: ['Bihar'],
      eligibleOccupations: ['Self-Employed', 'Business Owner / MSME', 'Artisan / Craftsperson', 'Unemployed'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Intermediate / 10+2 / ITI / Polytechnic / Degree Certificate', 'Bihar Domicile Certificate', 'Caste Certificate', 'Current Bank Account Details of Entity'],
    applicationProcess: ['Apply online on udyami.bihar.gov.in when applications open.', 'Selection done through computerized lottery system.', 'Two-week enterprise training provided before fund release.'],
    officialUrl: 'https://udyami.bihar.gov.in/',
    helplineNumber: '1800-345-6214',
    tags: ['Bihar', 'MSME Startup', '5 Lakh Grant', 'Udyami Yojana', 'State Scheme'],
  },

  // ==========================================
  // 11. KERALA STATE SCHEMES
  // ==========================================
  {
    title: 'Karunya Benevolent Fund (KBF - Kerala)',
    slug: 'kerala-karunya-benevolent-fund',
    categorySlug: 'health-wellness',
    ministry: 'Health and Family Welfare Department, Government of Kerala',
    department: 'State Health Agency (SHA) Kerala',
    schemeLevel: 'State',
    state: 'Kerala',
    shortDescription: 'Financial grant up to ₹2,00,000 to ₹3,00,000 for poor patients suffering from cancer, cardiac diseases, and kidney failure in Kerala.',
    description: 'Karunya Benevolent Fund (funded through Karunya lottery proceeds) provides financial assistance up to ₹2 Lakh (and up to ₹3 Lakh for kidney transplants) to low-income families in Kerala for treating severe chronic and catastrophic illnesses.',
    benefitType: 'Subsidy',
    financialBenefit: 'Direct medical treatment grant up to ₹2,00,000 (up to ₹3,00,000 for kidney/liver transplants)',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 100,
      gender: 'All',
      maxIncome: 300000,
      eligibleStates: ['Kerala'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Medical Treatment Certificate from Government Hospital Specialist', 'Income Certificate (< ₹3 Lakh)', 'Aadhaar Card', 'Ration Card of Kerala'],
    applicationProcess: ['Submit application to District Committee chaired by District Collector.', 'Funds directly credited to hospital for patient treatment.'],
    officialUrl: 'http://karunya.kerala.gov.in/',
    helplineNumber: '1056 / 0471-2555722',
    tags: ['Kerala', 'Critical Illness', 'Cancer Grant', 'Kidney Care', 'State Scheme'],
  },
  {
    title: 'Subhiksha Keralam (Kerala)',
    slug: 'kerala-subhiksha-keralam',
    categorySlug: 'agriculture-rural-development',
    ministry: 'Agriculture Development and Farmers Welfare Department, Government of Kerala',
    department: 'Directorate of Agriculture Kerala',
    schemeLevel: 'State',
    state: 'Kerala',
    shortDescription: 'Subsidies and inputs for converting fallow land into integrated farming, animal husbandry, and aquaculture.',
    description: 'Subhiksha Keralam focuses on food self-sufficiency in Kerala by supporting fallow land cultivation of paddy, tubers, vegetables, and pulses with input subsidies of ₹40,000/hectare, interest-free cooperative credit, and integrated dairy/poultry kits.',
    benefitType: 'Subsidy',
    financialBenefit: 'Up to ₹40,000/hectare input subsidy + interest subvention loans through cooperative banks',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 75,
      gender: 'All',
      maxIncome: 1200000,
      eligibleStates: ['Kerala'],
      eligibleOccupations: ['Farmer', 'Self-Employed'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Land Possession Certificate / Fallow Land Lease Agreement', 'Aadhaar Card', 'Bank Passbook'],
    applicationProcess: ['Register on AIMS portal (aims.kerala.gov.in).', 'Krishi Bhavan Agricultural Officer conducts site inspection and sanctions subsidy.'],
    officialUrl: 'https://aims.kerala.gov.in/',
    helplineNumber: '0471-2304480',
    tags: ['Kerala', 'Fallow Land Cultivation', 'Food Security', 'Agriculture', 'State Scheme'],
  },

  // ==========================================
  // 12. TELANGANA & ANDHRA PRADESH SCHEMES
  // ==========================================
  {
    title: 'Rythu Bandhu / Rythu Bharosa (Telangana & AP)',
    slug: 'telangana-ap-rythu-bandhu-bharosa',
    categorySlug: 'agriculture-rural-development',
    ministry: 'Department of Agriculture and Farmers Welfare, Government of Telangana',
    department: 'Commissionerate of Agriculture',
    schemeLevel: 'State',
    state: 'Telangana',
    shortDescription: 'Investment support of ₹10,000 to ₹15,000 per acre per year for two crop seasons directly transferred to farmers.',
    description: 'This landmark agrarian investment support scheme provides ₹5,000 to ₹7,500 per acre per season (₹10,000 to ₹15,000/acre/year) directly into farmers bank accounts ahead of Kharif and Rabi seasons to purchase seeds, fertilizers, and ploughing inputs without predatory moneylenders.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹10,000 to ₹15,000 per acre per year direct cash assistance credited before sowing seasons',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 85,
      gender: 'All',
      maxIncome: 2500000,
      eligibleStates: ['Telangana', 'Andhra Pradesh'],
      eligibleOccupations: ['Farmer'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Pattadar Passbook (Dharani Portal Record)', 'Aadhaar Card', 'Bank Account Passbook'],
    applicationProcess: ['Agricultural Extension Officer verifies land records via Dharani.', 'Funds credited directly through Treasury portal.'],
    officialUrl: 'http://rythubandhu.telangana.gov.in/',
    helplineNumber: '040-23383520',
    tags: ['Telangana', 'Andhra Pradesh', 'Farmer Investment', 'Rythu Bandhu', 'State Scheme'],
  },
  {
    title: 'Aarogyasri Health Scheme (Andhra Pradesh & Telangana)',
    slug: 'andhra-telangana-aarogyasri-health-scheme',
    categorySlug: 'health-wellness',
    ministry: 'Health, Medical and Family Welfare Department, Government of Andhra Pradesh',
    department: 'Dr. YSR Aarogyasri Health Care Trust',
    schemeLevel: 'State',
    state: 'Andhra Pradesh',
    shortDescription: 'End-to-end cashless medical treatment cover up to ₹5,00,000 to ₹25,00,000 across 3,257 procedures in empaneled hospitals.',
    description: 'Dr. YSR Aarogyasri / Aarogyasri Telangana provides comprehensive cashless tertiary care covering 3,257 surgical and medical therapies up to ₹25 Lakh for catastrophic treatments, including post-operative subsistence allowance (Aarogya Aasara ₹225/day) during recuperation.',
    benefitType: 'Insurance',
    financialBenefit: 'Cashless hospital treatment up to ₹25,00,000 + post-operative recovery wage allowance up to ₹5,000/month',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 100,
      gender: 'All',
      maxIncome: 500000,
      eligibleStates: ['Andhra Pradesh', 'Telangana'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aarogyasri Card / Rice Card (BPL)', 'Aadhaar Card'],
    applicationProcess: ['Meet Vaidya Mithra at empaneled hospital.', 'Instant online pre-authorization and cashless hospital admission.'],
    officialUrl: 'https://www.aarogyasri.ap.gov.in/',
    helplineNumber: '104',
    tags: ['Andhra Pradesh', 'Telangana', 'Cashless Hospital', 'Aarogyasri', 'State Scheme'],
  },
  {
    title: 'Kalyana Lakshmi / Shaadi Mubarak (Telangana)',
    slug: 'telangana-kalyana-lakshmi-shaadi-mubarak',
    categorySlug: 'social-welfare-inclusion',
    ministry: 'Backward Classes and Minority Welfare Department, Government of Telangana',
    department: 'Telangana e-Pass',
    schemeLevel: 'State',
    state: 'Telangana',
    shortDescription: 'One-time financial gift of ₹1,00,116 for marriage of unmarried girls from poor SC, ST, BC, and minority families.',
    description: 'Kalyana Lakshmi and Shaadi Mubarak provides a one-time wedding financial gift of ₹1,00,116 directly into the bank account of the bride mother at the time of marriage, eliminating the debt trap of marriage expenses and curbing child marriages.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹1,00,116 one-time direct cash gift credited before marriage ceremony',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 35,
      gender: 'Female',
      maxIncome: 200000,
      eligibleStates: ['Telangana'],
      eligibleOccupations: ['Student', 'Unemployed', 'Other'],
      eligibleCategories: ['SC', 'ST', 'OBC'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Bride Age Proof (18+ Birth Certificate / SSC Marksheet)', 'Bride Mother Bank Passbook', 'Income Certificate (< ₹2 Lakh)', 'Wedding Card / Marriage Certificate'],
    applicationProcess: ['Apply online on telanganaepass.cgg.gov.in before marriage.', 'Tahsildar conducts field inquiry and sanctions amount.'],
    officialUrl: 'https://telanganaepass.cgg.gov.in/',
    helplineNumber: '040-23390228',
    tags: ['Telangana', 'Marriage Grant', '1 Lakh Wedding Gift', 'Kalyana Lakshmi', 'State Scheme'],
  },

  // ==========================================
  // 13. ODISHA STATE SCHEMES
  // ==========================================
  {
    title: 'KALIA Scheme (Krushak Assistance for Livelihood and Income Augmentation - Odisha)',
    slug: 'odisha-kalia-scheme',
    categorySlug: 'agriculture-rural-development',
    ministry: 'Department of Agriculture and Farmers Empowerment, Government of Odisha',
    department: 'Directorate of Agriculture and Food Production',
    schemeLevel: 'State',
    state: 'Odisha',
    shortDescription: 'Income support of ₹10,000/year for small/marginal farmers and ₹12,500 livelihood grant for landless farm workers.',
    description: 'KALIA scheme is a pioneering social safety net in Odisha providing ₹10,000 annually in two installments to small and marginal farmers, ₹12,500 non-farm livelihood cash assistance for landless agrarian households, and interest-free crop loans up to ₹1,00,000.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹10,000/year farm input grant + ₹12,500 livelihood grant for landless + 0% interest crop loan up to ₹1 Lakh',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 75,
      gender: 'All',
      maxIncome: 150000,
      eligibleStates: ['Odisha'],
      eligibleOccupations: ['Farmer'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aadhaar Card', 'Ration Card', 'Land Record / Landless Agrarian Undertaking', 'Bank Passbook'],
    applicationProcess: ['Apply at Gram Panchayat camp or on kalia.odisha.gov.in.', 'District Committee approves list for direct DBT.'],
    officialUrl: 'https://kalia.odisha.gov.in/',
    helplineNumber: '1800-572-1122',
    tags: ['Odisha', 'Farmer Support', 'KALIA Scheme', 'Landless Workers', 'State Scheme'],
  },
  {
    title: 'Biju Swasthya Kalyan Yojana (BSKY - Odisha)',
    slug: 'odisha-biju-swasthya-kalyan-yojana',
    categorySlug: 'health-wellness',
    ministry: 'Health and Family Welfare Department, Government of Odisha',
    department: 'State Health Assurance Society Odisha',
    schemeLevel: 'State',
    state: 'Odisha',
    shortDescription: 'Cashless healthcare cover up to ₹5,00,000 for male and ₹10,00,000 for female family members in Odisha.',
    description: 'BSKY provides universal free healthcare services in all government hospitals and up to ₹5 Lakh cashless coverage (enhanced to ₹10 Lakh for female family members) per family per year in 800+ empaneled private hospitals inside and outside Odisha.',
    benefitType: 'Insurance',
    financialBenefit: 'Cashless cover up to ₹5,00,000 per family per year (₹10,00,000 for female members)',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 100,
      gender: 'All',
      maxIncome: 300000,
      eligibleStates: ['Odisha'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['BSKY Smart Health Card / Ration Card', 'Aadhaar Card'],
    applicationProcess: ['Present BSKY Smart Health Card at BSKY Helpdesk at empaneled hospital for instant cashless admission.'],
    officialUrl: 'https://bsky.odisha.gov.in/',
    helplineNumber: '104 / 155369',
    tags: ['Odisha', 'Cashless Hospital', 'Women 10 Lakh', 'BSKY', 'State Scheme'],
  },

  // ==========================================
  // 14. PUNJAB & HARYANA SCHEMES
  // ==========================================
  {
    title: 'Aam Aadmi Clinic / Sehat Bima (Punjab)',
    slug: 'punjab-aam-aadmi-clinic-sehat-bima',
    categorySlug: 'health-wellness',
    ministry: 'Department of Health and Family Welfare, Government of Punjab',
    department: 'Punjab Health Systems Corporation',
    schemeLevel: 'State',
    state: 'Punjab',
    shortDescription: 'Free clinical consultations, 80+ lab diagnostic tests, and 180+ medicines at 800+ neighborhood community clinics in Punjab.',
    description: 'Aam Aadmi Clinics in Punjab provide free walk-in primary outpatient healthcare, over 80 diagnostic tests (including blood, diabetes, thyroid, and renal tests), and 180 essential medications without any registration fee or doctor consultation charge.',
    benefitType: 'In-Kind Support',
    financialBenefit: '100% free doctor consultations + 80+ free lab diagnostic tests + 180+ free essential prescription medicines',
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 100,
      gender: 'All',
      maxIncome: 10000000,
      eligibleStates: ['Punjab'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Employed / Salaried', 'Unemployed', 'Student', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Aadhaar Card / Punjab Domicile Proof'],
    applicationProcess: ['Walk in directly to nearest Aam Aadmi Clinic with Aadhaar card.', 'Consult doctor and collect medicines at pharmacy counter.'],
    officialUrl: 'https://health.punjab.gov.in/',
    helplineNumber: '104',
    tags: ['Punjab', 'Neighborhood Clinic', 'Free Medicines', 'Free Lab Tests', 'State Scheme'],
  },
  {
    title: 'Mukhyamantri Parivar Samriddhi Yojana (MMPSY - Haryana)',
    slug: 'haryana-mukhyamantri-parivar-samriddhi-yojana',
    categorySlug: 'social-welfare-inclusion',
    ministry: 'Finance Department, Government of Haryana',
    department: 'Citizen Resources Information Department (CRID)',
    schemeLevel: 'State',
    state: 'Haryana',
    shortDescription: 'Social security financial benefit of ₹6,00,0 per year for families with annual income up to ₹1,80,000.',
    description: 'MMPSY provides annual social security assistance of ₹6,000 per year directly to families in Haryana verified through Parivar Pehchan Patra (PPP) earning under ₹1.80 Lakh, covering premium for life insurance, accidental insurance, and pension schemes.',
    benefitType: 'Direct Benefit Transfer',
    financialBenefit: '₹6,000 per year direct financial assistance + insurance/pension premium coverage',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 60,
      gender: 'All',
      maxIncome: 180000,
      eligibleStates: ['Haryana'],
      eligibleOccupations: ['Farmer', 'Artisan / Craftsperson', 'Street Vendor', 'Self-Employed', 'Unemployed', 'Other'],
      eligibleCategories: ['All'],
      requiresDisability: false,
      requiredSpecialStatus: [],
    },
    requiredDocuments: ['Parivar Pehchan Patra (Family ID)', 'Aadhaar Card', 'Bank Account Details'],
    applicationProcess: ['Apply at Saral Haryana Kendra or through meraparivar.haryana.gov.in portal.', 'Amount credited directly based on PPP verified income.'],
    officialUrl: 'https://cm-psy.haryana.gov.in/',
    helplineNumber: '1800-200-0023',
    tags: ['Haryana', 'Social Security', 'Parivar Pehchan Patra', 'MMPSY', 'State Scheme'],
  },
];
